name: GitHub Actions CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNING_IN_CI: True
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Testing with version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versioon }}
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome driver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb
      - name: Install Firefox driver
        run: |
          wget -N https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -P ~/
          tar -xzf ~/geckodriver-v0.26.0-linux64.tar.gz -C ~/
          rm ~/geckodriver-v0.26.0-linux64.tar.gz
          sudo mv -f ~/geckodriver /usr/local/share
          sudo chmod +x /usr/local/share/geckodriver
          sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

      - name: Install Edge driver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo rm microsoft.gpg
          sudo apt update
          sudo apt install microsoft-edge-dev
          wget https://msedgedriver.azureedge.net/97.0.1069.0/edgedriver_linux64.zip -P ~/
          unzip ~/edgedriver_linux64.zip -d ~/
          rm ~/edgedriver_linux64.zip
          sudo mv -f ~/msedgedriver /usr/local/share/
          sudo chmod 777 /usr/local/share/msedgedriver
          sudo ln -s /usr/local/share/msedgedriver /usr/local/bin/msedgedriver

      - name: Run Tests
        run: |
          python -m unittest discover tests

      - name: Install pypa/build
        run: |  
          python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python3 -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
