name: GitHub Actions CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Testing with version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versioon }}
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome driver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb
      - name: Install Firefox driver
        run: |
          wget -N https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -P ~/
          tar -xzf ~/geckodriver-v0.26.0-linux64.tar.gz -C ~/
          rm ~/geckodriver-v0.26.0-linux64.tar.gz
          sudo mv -f ~/geckodriver /usr/local/share
          sudo chmod +x /usr/local/share/geckodriver
          sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

      - name: Run Tests
        run: |
          python -m unittest discover tests
